### ISSUE TITLE
Publication format

### ISSUE THREAD

**Issue by jc5201** [ml-postech/ml-postech.github.io#11]
안성수 교수님께서 의견 내주셨는데 
publication page의 학회 이름들이 통일되어  있지 않은 것 같아서 형식 통일하면 좋을 것 같습니다. 

예를 들면 
```
Thirty-Fifth Conference on Neural Information Processing Systems,
Advances in Neural Information Processing Systems,
```

bibtex 의 @STRING 사용해서 통일하는 것도 좋을 것 같은데 (https://github.com/ml-postech/ml-postech.github.io/commit/6122da176aa47b6cc0d3ef1a15b52e099828ab51)
bibtex_js 에 뭔가 문제가 있는지 작동이 안되네요.

**Comment by dongwookim-ml** [comment]
bibtex_js를 뜯어봐야할 것 같은데요. 최신버전을 먼저 확인해봐야할까요?

**Comment by seunghyukcho** [comment]
학회들의 이름들을 bibtex 상에서 @STRING 을 사용하여 정리했습니다.

약어가 불명확한 저널들이나 workshop들은 추후 format을 통일하여 정리할 예정입니다.
